samaritanministries/paragon

gatsby-config.js, package.json, src/components/codetoggle-scss.js, src/components/codetoggle.js, src/components/layout.js, src/pages/components/actions/code.js, src/pages/get-started.js, src/sass/example-page/prism.scss
- add prismjs as a plugin
- fix firefox pre and code so that it wraps
=> Prism Plugin

gatsby-config.js, package.json, src/components/codetoggle-scss.js, src/components/codetoggle.js, src/components/layout.js, src/pages/components/accordion/code.js, src/pages/components/actions/code.js, src/pages/components/actions/guidelines.js, src/pages/components/cards/code.js, src/pages/components/forms/code.js, src/pages/components/navigation/code.js, src/pages/components/overpanel/code.js, src/pages/get-started.js, src/pages/templates/default.js, src/pages/templates/grid.js, src/pages/templates/header.js, src/pages/templates/mobile.js, src/pages/templates/sign-in.js, src/pages/templates/single-page.js, src/sass/base/extendables/_extendables.scss, src/sass/base/mixins/_mixins.scss, src/sass/dashboard/placeholder.scss, src/sass/dashboard/sidebar.scss, src/sass/example-page/example-page.scss, src/sass/example-page/prism.scss, src/sass/modules/actions/README.md, src/sass/modules/actions/_actions.scss, src/sass/modules/actions/_toggle-button.scss
- BIG update to action example page
- Update to navigation example page
- Refactored `actions.scss`
- `button--icon--small` now uses `button--icon`
- Updated menu icon name to be more semantically correct
=> Button refactor

src/pages/components/accordion/code.js, src/pages/components/actions/code.js, src/pages/components/banner/code.js, src/pages/components/cards/code.js, src/pages/components/checkboxes/code.js, src/pages/components/css-grid/code.js, src/pages/components/footer/code.js, src/pages/components/forms/code.js, src/pages/components/lists/code.js, src/pages/components/navigation/code.js, src/pages/components/overpanel/code.js, src/pages/components/progress-stepper/code.js, src/pages/components/radio-buttons/code.js, src/pages/components/spinner/code.js, src/pages/components/tables/code.js, src/pages/components/tags/code.js, src/pages/components/toggle/code.js, src/sass/example-page/example-page.scss
This replaces for now the old copy link feature per section. This places the id in the url and allows you to copy/paste it on your own from the browser bar.
=> Add to url

src/pages/components/navigation/code.js, src/pages/templates/default.js, src/sass/experimental/mobilemenu.scss, src/sass/experimental/placeholder.scss
- import placeholder and mobile menu per module needing them
- remove mobile nav from navigation examples
=> Fix Example Pages

src/pages/components/accordion/code.js, src/sass/modules/accordion/_accordion.scss
- Add accordion--footer to example page
- Remove jquery slideToggle (change to display: block/none)
=> Accordion animation removal

src/pages/components/forms/code.js, src/sass/experimental/mobilemenu.scss, src/sass/experimental/placeholder.scss, src/sass/modules/forms/forms.scss
Add a class to the `fieldset` to add optional text to it
=> Add optional label to fieldsets via class

src/pages/templates/default.js, src/sass/example-page/image.scss, src/sass/experimental/mobilemenu.scss, src/sass/experimental/placeholder.scss, src/sass/experimental/x-paragon.scss, src/sass/modules/navigation/navigation.scss
- Add `x-paragon.scss` file (this duplicates `paragon.scss`, but with importing experimental folder)
- Remove double imports from `placeholder.scss` and `mobilemenu.scss` files
=> Rearrange experimental files

src/components/sidebar.js, src/pages/components/forms/code.js, src/pages/components/modal/code.js, src/pages/components/modal/defaultmodal.js, src/pages/components/modal/guidelines.js, src/sass/experimental/mobilemenu.scss, src/sass/experimental/placeholder.scss, src/sass/modules/modal/modal.scss
- Add a modal example page
- Add modal enter animation
- Change name away from `dash-modal`
=> Add Modal examples

src/components/sidebar.js, src/pages/style/spacing/code.js, src/pages/style/spacing/guidelines.js, src/sass/base/utilities/_utilities.scss, src/sass/example-page/example-page.scss
- Added spacing utility styles to code guidelines
- Missing guidelines page still
=> added spacing code

src/sass/modules/accordion/_accordion.scss, src/sass/modules/table/table.scss, src/sass/modules/tags/tags.scss, src/sass/modules/typography/_typography.scss
=> Remove underlines for tags, actions, and tables

src/pages/templates/responsive-forms.js, src/sass/modules/forms/forms.scss
Seen issues with our `flex-content` --> `flex-row` items getting too small on tablet. Did some adjusting to give the `fieldsets` a min-width and also margin left instead of right (for wrapping purposes).
=> Update flex-content responsive code

src/sass/base/variables/variables.scss, src/sass/example-page/example-page.scss, src/sass/experimental/mobilemenu.scss, src/sass/modules/forms/themed-elements.scss, src/sass/modules/modal/modal.scss, src/sass/modules/navigation/navigation.scss, src/sass/modules/overpanel/overpanel.scss, src/sass/modules/spinner/spinner.scss
Did some research around z-index management and using variables seemed to be widely used. Let me know what you guys think. I _think_ I caught all the different areas we used z-index.
=> Use variables for z-index

src/pages/components/icons/code.js, src/sass/base/utilities/_utilities.scss, src/sass/example-page/example-page.scss, src/sass/modules/icons/icons.scss
- Added icon examples for using icons with text (header & content)
- Added flex utilities
- Added icon color examples to Paragon
---
=> Icon & Flex Utility Updates

src/pages/templates/default.js, src/sass/base/mixins/_mixins.scss, src/sass/example-page/color.scss, src/sass/example-page/example-page.scss, src/sass/example-page/prism.scss, src/sass/example-page/typography.scss, src/sass/experimental/mobilemenu.scss, src/sass/experimental/placeholder.scss, src/sass/modules/banner/_banner.scss, src/sass/modules/forms/forms.scss, src/sass/modules/forms/themed-elements.scss, src/sass/modules/icons/icons.scss, src/sass/modules/navigation/navigation.scss, src/sass/modules/overpanel/overpanel.scss, src/sass/modules/progress-stepper/progress-stepper.scss, src/sass/modules/table/table.scss, src/sass/modules/tags/tags.scss, src/sass/modules/tooltip/_tooltip.scss, src/sass/modules/typography/_typography.scss
Change active page underline to teal. Add animation on hover. Add border-bottom to main header.
Add sticky header to overpanel.
- This keeps the header at the top when scrolling an overpanel
=> Nav bar update

src/pages/components/banner/code.js, src/pages/templates/default.js, src/pages/templates/global-banner.js, src/sass/example-page/example-page.scss, src/sass/modules/banner/_banner.scss, src/sass/modules/navigation/navigation.scss
Global Banner styles
- Added banner examples to Paragon
- Reformatted banners to have shared styles
=> Global Banner styles

src/pages/style/accessibility/guidelines.js, src/pages/style/spacing/code.js, src/sass/base/utilities/_utilities.scss, src/sass/modules/forms/forms.scss
#100 
---
#94 
---
#99 
---
Add `space-none` and `none` to apply margin or padding of 0.
Examples:
- `mr-space-none` = `margin-right: 0;`
- `mr-none` = `margin-right: 0;`
=> Issue updates

src/components/layout.js, src/pages/components/cards/guidelines.js, src/sass/base/utilities/_utilities.scss
Add code for utility classes.
_(examples will be added when we get a dedicated utility page)_
Fixes #118 
Fixes #117
=> Display utility classes

package-lock.json, package.json, src/sass/modules/spinner/spinner.scss
Resolves issue #120 
Looks like package-lock.json and package.json updated? Should it?
=> Border button spinner

src/components/layout.js, src/pages/components/footer/code.js, src/pages/index.js, src/pages/templates/default-long-content.js, src/pages/templates/default.js, src/pages/templates/footer.js, src/sass/example-page/example-page.scss, src/sass/modules/footer/footer.scss, src/sass/modules/navigation/navigation.scss
Add footer example page: http://localhost:8000/components/footer/code
Add to default template page: http://localhost:8000/templates/default/
=> Update web footer

src/components/sidebar.js, src/pages/components/banner/code.js, src/pages/components/banner/guidelines.js, src/pages/components/toasts/code.js, src/pages/components/toasts/guidelines.js, src/pages/components/toasts/toast.js, src/pages/templates/default.js, src/sass/base/variables/variables.scss, src/sass/example-page/example-page.scss, src/sass/experimental/toast.scss, src/sass/modules/_modules.scss, src/sass/modules/toast/toast.scss
- Add HTML/CSS for toast messages
- Add example page for the component and guidelines to best practices
- Add React component for Toasts
=> Add Toast component

src/sass/base/colors/_given-colors.scss
=> Update gradient color

package-lock.json, src/pages/components/navigation/code.js, src/pages/components/navigation/subnav.js, src/pages/templates/default-subnav.js, src/pages/templates/default.js, src/sass/base/mixins/_mixins.scss, src/sass/base/variables/variables.scss, src/sass/modules/navigation/navigation.scss, src/sass/modules/typography/_typography.scss
A lot going on here... But here are the main points:
- Created a React Component for the SubNav so I could easily add/remove the title in examples
- Created a mixin for the dropdown menu so the styles could be shared. Used a mixin because I could apply that within a media query (since the dropdown ONLY shows up on mobile). It is kind of a weird setup and probably not the most efficient, but works and am able to share code.
- Created a new default template page with the subnav and title so I could test it properly.
- Moved the typography variables into the `variables.scss` file because I needed access to them for the mixin
- Had to write a few custom styles for the subnav for when the title is showing
You can run it locally and test out the example page: …
=> Title in subnav

src/pages/components/navigation/code.js, src/pages/components/navigation/global-navigation.js, src/pages/components/navigation/mobilemenu.js, src/pages/templates/default-long-content.js, src/pages/templates/default-subnav.js, src/pages/templates/default.js, src/pages/templates/global-banner.js, src/pages/templates/responsive-forms.js, src/sass/example-page/example-page.scss, src/sass/experimental/experimental.scss, src/sass/experimental/mobilemenu.scss, src/sass/modules/_modules.scss, src/sass/modules/navigation/mobile-menu.scss, src/sass/modules/navigation/navigation.scss
- Add mobile menu scss to Paragon
- Show mobile menu button on mobile in navigation examples
- Build out global navigation component for make rendering templates easier
- Add mobile menu to template examples
=> Add mobile menu

src/sass/modules/css-grid/css-grid-fallbacks.scss, src/sass/modules/css-grid/css-grid-main.scss, src/sass/modules/css-grid/css-grid-mixins.scss
=> Css grid refactor

src/pages/components/navigation/code.js, src/sass/modules/navigation/navigation.scss
Add code and example for sub navigation back button.
=> Add back button to subnav

src/sass/CHANGELOG.md, src/sass/modules/css-grid/css-grid-main.scss, src/sass/package.json
Adds back the code that removed the margin of cards within a grid.
=> Remove card margin within a grid

.stylelintignore, src/pages/style/typography/guidelines.js, src/paragon-framework/actions/_actions.scss, src/paragon-framework/actions/button-mixins.scss, src/paragon-framework/actions/button-theme-dark.scss, src/paragon-framework/actions/button-theme-default.scss, src/paragon-framework/actions/button-theme-light.scss, src/paragon-framework/actions/button.scss, src/paragon-framework/base/variables/variables.scss, src/paragon-framework/grid/grid-fallbacks.scss, src/paragon-framework/grid/grid-main.scss, src/paragon-framework/grid/grid-mixins.scss, src/paragon-framework/theme/_theme.scss
When we changed the base font size to 16px, we forgot to change the guidelines.
=> Update typography docs for new base font size

src/paragon-framework/modules/avatar/_avatar.scss, src/paragon-framework/modules/navigation/navigation.scss
- Removed extra code for hover animations on main and sub navigation (#157 )
- Fix safari profile image bug
=> Navigation animation refactor

src/paragon-framework/modules/spinner/spinner.scss, src/paragon-framework/modules/table/table.scss
- Remove float from spinners. Not needed anymore!
- Added an important to loading table animations to help when we have super specific table classes (condensed, font small, etc.)
=> Spinner and Loading Table updates

src/paragon-framework/base/utilities/_utilities.scss, src/paragon-framework/modules/forms/forms.scss
Added a few utility classes that were in our other applications.
=> Add new utility classes
