samaritanministries/paragon

src/sass/modules/actions/_actions.scss
With the recent merge, default button icons reverted to blue. This makes them gray(t) again.
=> Fixes color of default button-icons

src/sass/modules/forms/forms.scss
Seems standard practice to position dropdown arrow relative to the top. This would break if our input label somehow became more then 1 line... but other design system drop-downs break from the same occurrence.
=> Position dropdown arrow relative to top

src/sass/modules/actions/_actions.scss
Fixes #49 
Added top margin to block buttons that are NOT the first child. This makes sure they are stacked nice on all screen sizes.
=> Adjust margin on button--block for better stacking

src/sass/modules/card/_card.scss
**Remove card padding on mobile**
This code recently got removed from Paragon. But cards will now go up to the side of the screen on mobile.
**Properly adjust card margin for use in grid**
Removed card margin if it is the last card within a grid. This keeps this card margin from doubling up the `grid-padding`
=> Mobile Card & Card Margin

src/sass/modules/accordion/_accordion.scss, src/sass/modules/card/_card.scss
This is what it looked like... broken
The code was giving the grid within a card negative margin on mobile instead of the card itself.
=> Fix broken grid with card

src/sass/modules/card/_card.scss
When there was a `.card` within another `.card` our code would remove the margin for both, making it look terrible. Code checks to see if the `.card` has a parent of `.card-content`. 
This is what it looks like now:
This is what it looks like after the code change:
=> Don't remove margin from a card within another card

src/sass/example-page/example-page.scss, src/sass/modules/actions/_actions.scss, src/sass/modules/banner/_banner.scss, src/sass/modules/navigation/navigation.scss, src/sass/modules/typography/_typography.scss
Wanted to get the discussion started on focus styles... let me know your thoughts, concerns, etc.
_Note: None of this has been device tested yet_
---
**Links**
Add default focus ring on focus
Add text-decoration underline to link on hover/focus
**Actions**
Custom focus style on tab
- Utilized the box-shadow custom checkboxes and radio buttons use for hover
=> Improved Focus Styles

src/pages/components/css-grid/code.js, src/pages/templates/default.js, src/sass/modules/css-grid/css-grid-fallbacks.scss, src/sass/modules/css-grid/css-grid-main.scss, src/sass/modules/css-grid/css-grid-mixins.scss
Add `_desktop` to all CSS Grid classes to allow responsive adjustment.
@Nevren you might want to check my additions to your CSS Grid files. Also, could use your other Mac to test IE. :)
**Tablet**
**Desktop**
=> Add CSS Grid desktop sizing classes

src/pages/templates/default.js, src/sass/example-page/example-page.scss
So we used to import the experimental files for the example pages. This caused some files to be double imported... moved this import to the default template.
Looks to have fixed it...
=> Move experimental file import

src/pages/components/overpanel/code.js, src/pages/templates/overpanel-example.js, src/sass/modules/overpanel/overpanel.scss
Overpanel code did not have the slide up animation code. Added this and also called it out in the example page.
Also, with using the overpanel `position: fixed;` seemed to work better. This keeps the overpanel in view when the background content is longer then the overpanel.
=> Add overpanel animation to component

src/pages/components/cards/code.js, src/pages/components/overpanel/code.js, src/pages/templates/overpanel-example.js, src/sass/experimental/mobilemenu.scss, src/sass/modules/accordion/_accordion.scss, src/sass/modules/card/_card.scss, src/sass/modules/overpanel/overpanel.scss, src/sass/modules/typography/_typography.scss
These styling bugs were noticed on mobile devices when doing device testing.
---
Fix loading card animation for mobile
- This looked weird, didn't like the `overflow: hidden;` on the `card-header`. Had to add it to each item.
Adjust overpanel styling on mobile
- Adjust header font size on smaller screen
- Fix mobile scrolling
Adjust Accordion title and subtitle font size on mobile
Make `<a>` tags with a `button` class inline-block
=> Overpanel, Loading Card, <a> tag adjustments

src/sass/modules/forms/card-controls.scss, src/sass/modules/forms/forms.scss, src/sass/modules/forms/themed-elements.scss
Fixes #51 
Fixes #77 
The labels were not aligning properly with the radio buttons. Also, the radio/checkbox cards were not stacking very nicely on mobile. Adjusted that as well. 
IE has the label wrapping under the radio button, but it looks like it does that right now.
---
**Broken Styles**
---
**Fixed Styles**
---
This has been devices tested across all devices and working well.
=> Fix Radio/Checkbox Button labels

src/sass/modules/card/_card.scss, src/sass/modules/typography/_typography.scss
A selectable card list is setup to have the `li` be the link. But in React we add an `a` tag nested inside of the `li` tag to make it a link.
The added code will keep the padding consistent for both setups.
Also, added a utility class to remove the decoration that an `a` tag gets by default. For this use case... the `a` tag being a link for the entire row.
=> Card List plus React link

src/sass/modules/forms/forms.scss
Fixes #59 
Did this for radio buttons, checkboxes, and the radio/checkbox cards within a `flex-row`
**Bad**
**Good**
=> Issue 59/radio button error

src/sass/base/variables/variables.scss
This PR addresses a couple things:
- Update media query breakpoints from `rem` to `px`
- Fixing an overlap issue that happens with the min and mix both having the same values.
_Making sure min breakpoints are even and max breakpoints are odd fix the issue of both breakpoint styles applying_
=> Fix breakpoint overlap

src/pages/components/banner/code.js, src/pages/components/banner/guidelines.js, src/pages/components/cards/code.js, src/pages/components/icons/code.js, src/sass/modules/card/_card.scss, src/sass/modules/icons/icons.scss
Removed `card-banner` and replaced with `card-info`. Using `card-info` as a banner and info card now.
Default state of the `card-info` is blue. Adding `.has-error`, `.has-success` or `.has-warning` will give it the appropriate styles.
Update the guidelines page for banners to reflect the new styles.
---
=> Update info card/card banner styles

src/pages/components/cards/guidelines.js, src/pages/components/icons/code.js, src/pages/style/spacing/code.js, src/sass/base/utilities/_utilities.scss, src/sass/modules/card/_card.scss, src/sass/modules/typography/_typography.scss
**Fixes the below issues:**
#113 : Make phone content 100% width
#106 : Fix link
#84 : Remove opacity change when using `.no-decoration`. Inherit colors instead of declaring them.
#88 : Updated code on icons page
#107 : Make the element the copy code it looking at more specific so it doesn't grab every `code` element on the page
---
Added new flex utilities.
Updated the margin/padding utility to have the ability to just apply on mobile.
=> Paragon Bug Fixes

.stylelintrc, src/sass/base/utilities/_utilities.scss, src/sass/modules/forms/forms.scss, src/sass/modules/table/table.scss
Fixed #128 
---
IE likes to have the units on Flex box shorthand. IF not, things start to look funky. Stylelint has a rule to remove these, so I disabled that rule.
=> Allow zero length units for IE. Update flex shorthand to add units.

src/sass/modules/card/_card.scss
Fixed #115 
---
If the banner did not have enough content, it would only be as wide as the content. Added a `min-width` to the item.
**Bonus:**
- Card Table had a black border on the top. Updated to our border color.
=> Add min-width to info cards

package.json, src/pages/components/tables/code.js, src/pages/components/tables/loadingTable.js, src/sass/base/extendables/_extendables.scss, src/sass/modules/card/_card.scss, src/sass/modules/table/table.scss
#127 
---
Took the loading card concept and applied it to Loading tables. Tried to keep the table headers, but show the loading bar instead of content.
- Added all the appropriate CSS
- Added a React component for the LoadingTable that can be copied over to the appropriate React apps for smoother implementation (Paragon examples are in HTML only though)
**Examples:**
---
=> Add loading Table examples / code

package-lock.json, package.json, src/components/tippyComponent.js, src/pages/components/clippy/code.js, src/pages/components/tooltip/code.js, src/sass/modules/tooltip/_tooltip.scss
The tippyjs react component we initially used was depreciated. They created a new package though, so updated Paragon to use that. Updated the main tippyjs package a couple major versions as well, which will fix the weird tooltip placement we have been seeing in the web app. Visually everything is the same just had to adjust a lot of class names/structure.
Resolves #131
=> Tippy.js upgrade

src/sass/modules/progress-stepper/progress-stepper.scss
With Progress step labels that are different length, setting the flex-basis to 0 was needed to make them all the same length.
=> Adjust flex on progress labels

src/pages/components/tags/code.js, src/sass/base/mixins/_mixins.scss, src/sass/modules/tags/tags.scss
Added `.is-selectable` class to apply if a tag needs to be clickable
Completes #119
=> Make default tag not-selectable

src/pages/components/icons/code.js, src/sass/modules/icons/icons.scss, src/sass/modules/tooltip/_tooltip.scss
Addresses #89 
- Add icon content and color values to scss maps (clean up the code a bit)
- Add examples for icon class utilities
- Change icon sizing to be relative to parent container
=> Add icon sizing utility classes

src/sass/modules/modal/modal.scss
When updating the icons to match its parent, the modal close button got a little huge. Made it go back to 1rem.
Was: 
Now:
=> Change modal close button to 1rem size
